// // quiz-fetcher/generateQuizSetMap.js
// const fs = require('fs');
// const path = require('path');

// const quizSetDir = path.join(__dirname, 'QuizSet'); // Local QuizSet folder
// const outputDir = path.join(__dirname, 'QuizSet');  // Save in same folder
// const outputFile = path.join(outputDir, 'quizSetMap.js'); // Will generate: QuizSet/quizSetMap.js

// // Read all JSON files
// const files = fs.readdirSync(quizSetDir).filter(file => file.endsWith('.json'));

// let outputLines = [];

// files.forEach(file => {
//   const key = file.replace('.json', ''); // e.g., 'cat9_easy_set1'
//   const relativePath = `./${file}`;      // relative to QuizSet directory
//   outputLines.push(`  '${key}': require('${relativePath}'),`);
// });

// const content = `// Auto-generated by generateQuizSetMap.js

// const quizSetMap = {
// ${outputLines.join('\n')}
// };

// export default quizSetMap;
// `;

// fs.writeFileSync(outputFile, content, 'utf8');
// console.log(`Successfully created: ${outputFile}`);
